"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import PageLayout from "./PageLayout";
import ReduxStoreProvider from "../store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxStoreProvider>
          <PageLayout>{children}</PageLayout>
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
